[request_definition]
r = sub, obj, act, amount, hour, sub_branch, obj_branch

[policy_definition]
p = sub, obj, act, cond

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act && eval(p.cond)
